name: Java CI with Maven, Docker Compose, and Flyway

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.7
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start PostgreSQL & Flyway via Docker Compose
        run: docker compose up -d

      - name: Wait for DB to be healthy
        run: |
          echo "Waiting for DB to become healthy..."
          for i in {1..10}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' $(docker ps -qf name=db))
            echo "Health status: $status"
            if [ "$status" == "healthy" ]; then
              echo "Database is healthy."
              break
            fi
            sleep 5
          done

      - name: Wait for Flyway to finish migration
        run: |
          echo "Waiting for Flyway to finish..."
          docker compose logs flyway

      - name: Ensure Maven wrapper is executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -B package

      - name: Submit dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
