name: Java CI with Maven, Docker Compose, and Flyway

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.7
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start PostgreSQL & Flyway via Docker Compose
        run: docker compose up -d

      - name: Wait for DB to be healthy
        run: |
          echo "Waiting for DB to become healthy..."
          for i in {1..10}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' $(docker ps -qf name=db))
            echo "Health status: $status"
            if [ "$status" == "healthy" ]; then
              echo "Database is healthy."
              break
            fi
            sleep 5
          done

      - name: Wait for Flyway to finish migration
        run: |
          echo "Waiting for Flyway to finish..."
          docker compose logs flyway

      - name: Ensure Maven wrapper is executable
        run: chmod +x ./mvnw

      - name: Run Tests and Generate Coverage Report
        run: ./mvnw -B clean test jacoco:report

      - name: Upload Coverage Report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: target/site/jacoco/
          retention-days: 30

      - name: Build with Maven
        run: ./mvnw -B package

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
          retention-days: 30

      - name: Display Test Summary
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ All tests passed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "- HTML Coverage Report: Available as artifact 'jacoco-coverage-report'" >> $GITHUB_STEP_SUMMARY
          echo "- Test Results: Available as artifact 'test-results'" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Download the coverage report artifact to view detailed coverage" >> $GITHUB_STEP_SUMMARY
          echo "2. Review test results in the uploaded artifacts" >> $GITHUB_STEP_SUMMARY

#      - name: Submit dependency graph
#        uses: advanced-security/maven-dependency-submission-action@v4

